### ISSUE TITLE
有关Minecraft服务器 超平坦 地形预设的问题

### ISSUE THREAD

**Issue by QSlotus** [shaokeyibb/Minecraft-Server-Starting-Guild#8]
我想问一下，MInecraft服务器超平坦的地形预设如何配置

**Comment by shaokeyibb** [comment]
可以在server.properties中指定generator-settings

**Comment by QSlotus** [comment]
> 可以在server.properties中指定generator-settings
想请教一下如何指定

**Comment by shaokeyibb** [comment]
> The settings used to customize world generation. Follow [its format](https://minecraft.fandom.com/wiki/Java_Edition_level_format#generatorOptions_tag_format) and write the corresponding JSON string. Remember to escape all : with \:.


https://minecraft.fandom.com/wiki/Server.properties

**Comment by QSlotus** [comment]
> 

好，谢谢，我去看看
